const val OFFICIAL_CONFIG2_VALUE1 = """
<Item ApkName="com.activision.callofduty.shooter">
    <Switch TextureId="86" Comment="弓箭" IdentificationId="" Name="Bow"/>
    <Switch TextureId="149" Comment="夜视仪开" IdentificationId="" Name="Nightvision"/>
    <Switch TextureId="95" Comment="开火模式" IdentificationId="" Name="FireMode2"/>
    <Switch TextureId="130" Comment="购物机向右标志" IdentificationId="" Name="ShoppingMachine"/>
    <Switch TextureId="57" Comment="更换背包" IdentificationId="" Name="SwitchBackpage"/>
    <Switch TextureId="129" Comment="CD的X" IdentificationId="" Name="CDX"/>
    <Switch TextureId="16" Comment="地图打开标志" IdentificationId="" Name="MapOpenFlag"/>
    <Switch TextureId="150" Comment="夜视仪关" IdentificationId="" Name="Nightvision1"/>
    <Switch TextureId="159" Comment="BR躲猫猫摄像头" IdentificationId="" Name="Brpeekaboo"/>
    <Switch TextureId="78" Comment="开局的黄色M" IdentificationId="" Name="YellowM"/>
    <Switch TextureId="171" Comment="战斗机" IdentificationId="" Name="jet"/>
    <Switch TextureId="168" Comment="喷气芯片喷气" IdentificationId="" Name="Blow"/>
    <Switch TextureId="111" Comment="礼物箱" IdentificationId="" Name="Gift"/>
    <Switch TextureId="11" Comment="跳伞（四人）" IdentificationId="" Name="Parachute4"/>
    <Switch TextureId="26" Comment="跳跃" IdentificationId="" Name="Jump"/>
    <Switch TextureId="133" Comment="坦克1" IdentificationId="" Name="Tank1"/>
    <Switch TextureId="68" Comment="弹跳" IdentificationId="" Name="Bounce"/>
    <Switch TextureId="71" Comment="烟雾弹" IdentificationId="" Name="Smoke"/>
    <Switch TextureId="165" Comment="2级背包" IdentificationId="" Name="Backpage2"/>
    <Switch TextureId="38" Comment="下潜" IdentificationId="" Name="SwimDown"/>
    <Switch TextureId="81" Comment="切换手雷" IdentificationId="" Name="SwitchGrenade"/>
    <Switch TextureId="115" Comment="闪光弹（躲猫猫）" IdentificationId="" Name="Flash2"/>
    <Switch TextureId="52" Comment="药物的加号" IdentificationId="" Name="XBtn"/>
    <Switch TextureId="127" Comment="趴下" IdentificationId="" Name="Fall"/>
    <Switch TextureId="151" Comment="暴风雨（团队模式）" IdentificationId="" Name="Rainstorm"/>
    <Switch TextureId="172" Comment="防空炮进" IdentificationId="" Name="AAgun"/>
    <Switch TextureId="58" Comment="方向轮盘" IdentificationId="" Name="SteeringWheel"/>
    <Switch TextureId="163" Comment="普通护甲" IdentificationId="" Name="Carmor"/>
    <Switch TextureId="189" Comment="新地图解锁2" IdentificationId="" Name="newmap2"/>
    <Switch TextureId="140" Comment="爬楼梯（团队模式）" IdentificationId="" Name="Stair"/>
    <Switch TextureId="13" Comment="开伞" IdentificationId="" Name="Parachute2"/>
    <Switch TextureId="51" Comment="白色向下箭头" IdentificationId="" Name="PickupDown"/>
    <Switch TextureId="61" Comment="选择开火模式的左边框" IdentificationId="" Name="SelectFireMode"/>
    <Switch TextureId="72" Comment="震爆弹" IdentificationId="" Name="Detonation"/>
    <Switch TextureId="54" Comment="取消趴下" IdentificationId="" Name="CancelFall"/>
    <Switch TextureId="24" Comment="蹲下" IdentificationId="" Name="Squat"/>
    <Switch TextureId="154" Comment="滑雪板跳" IdentificationId="" Name="Skijump"/>
    <Switch TextureId="6" Comment="乘车" IdentificationId="" Name="ByCar"/>
    <Switch TextureId="82" Comment="拾取防爆装置" IdentificationId="" Name="TrophySystem"/>
    <Switch TextureId="14" Comment="疾跑" IdentificationId="" Name="Run"/>
    <Switch TextureId="91" Comment="感应弹" IdentificationId="" Name="Induction"/>
    <Switch TextureId="155" Comment="防弹衣" IdentificationId="" Name="Armor"/>
    <Switch TextureId="1" Comment="开关门" IdentificationId="" Name="DoorOpen"/>
    <Switch TextureId="17" Comment="眼睛" IdentificationId="" Name="Eye"/>
    <Switch TextureId="144" Comment="选择手雷解锁鼠标（爆破模式）" IdentificationId="" Name="Boomf"/>
    <Switch TextureId="147" Comment="缆车（恶魔岛）" IdentificationId="" Name="Telpher"/>
    <Switch TextureId="62" Comment="拆弹）" IdentificationId="" Name="BombDisposal"/>
    <Switch TextureId="174" Comment="进入机甲" IdentificationId="" Name="Mecha"/>
    <Switch TextureId="34" Comment="刹车,按着" IdentificationId="" Name="Brake2"/>
    <Switch TextureId="60" Comment="更换武器）" IdentificationId="" Name="SwitchWeapon"/>
    <Switch TextureId="37" Comment="上潜" IdentificationId="" Name="SwimUp"/>
    <Switch TextureId="92" Comment="切换位置" IdentificationId="" Name="SwitchingPosition"/>
    <Switch TextureId="145" Comment="盾牌（团队模式）" IdentificationId="" Name="Shield1"/>
    <Switch TextureId="7" Comment="鸣笛" IdentificationId="" Name="Whistle"/>
    <Switch TextureId="42" Comment="下潜中" IdentificationId="" Name="SwimmingDown"/>
    <Switch TextureId="132" Comment="影刃（团队模式）" IdentificationId="" Name="ShadowBlade"/>
    <Switch TextureId="8" Comment="点开捡物" IdentificationId="" Name="ClickPickupDown"/>
    <Switch TextureId="180" Comment="拳套" IdentificationId="" Name="box"/>
    <Switch TextureId="185" Comment="直升机炮手" IdentificationId="" Name="gunner"/>
    <Switch TextureId="190" Comment="新地图解锁3" IdentificationId="" Name="newmap3"/>
    <Switch TextureId="181" Comment="塔奇克马载具机枪" IdentificationId="" Name="atv"/>
    <Switch TextureId="73" Comment="毒气弹" IdentificationId="" Name="Gas"/>
    <Switch TextureId="64" Comment="挂机后的边框" IdentificationId="" Name="HangUp"/>
    <Switch TextureId="98" Comment="语音按住" IdentificationId="" Name="Voice"/>
    <Switch TextureId="21" Comment="开火模式（左）" IdentificationId="" Name="FireMode1"/>
    <Switch TextureId="30" Comment="设置" IdentificationId="" Name="SetUp"/>
    <Switch TextureId="188" Comment="新地图解锁1" IdentificationId="" Name="newmap1"/>
    <Switch TextureId="69" Comment="展开" IdentificationId="" Name="Open"/>
    <Switch TextureId="83" Comment="连环闪光弹" IdentificationId="" Name="SerialFlash"/>
    <Switch TextureId="75" Comment="急救包" IdentificationId="" Name="FirstAidKit"/>
    <Switch TextureId="153" Comment="滑雪板" IdentificationId="" Name="Ski"/>
    <Switch TextureId="116" Comment="空投（一击必杀）" IdentificationId="" Name="Airdrop3"/>
    <Switch TextureId="162" Comment="异变围城购买解锁" IdentificationId="" Name="Change"/>
    <Switch TextureId="174" Comment="油门2" IdentificationId="" Name="Throttle2"/>
    <Switch TextureId="31" Comment="表情" IdentificationId="" Name="Emoji"/>
    <Switch TextureId="25" Comment="取消蹲下" IdentificationId="" Name="CancelSquat"/>
    <Switch TextureId="138" Comment="新空投" IdentificationId="" Name="Airdrop4"/>
    <Switch TextureId="43" Comment="鸣笛中" IdentificationId="" Name="Whistling"/>
    <Switch TextureId="121" Comment="抬头" IdentificationId="" Name="Moto1"/>
    <Switch TextureId="128" Comment="CD" IdentificationId="" Name="CD"/>
    <Switch TextureId="48" Comment="缆绳" IdentificationId="" Name="Cable"/>
    <Switch TextureId="152" Comment="歼灭者（团队模式）" IdentificationId="" Name="Annihilator"/>
    <Switch TextureId="164" Comment="高级护甲" IdentificationId="" Name="Aarmor"/>
    <Switch TextureId="28" Comment="取消瞄准" IdentificationId="" Name="Sniper2"/>
    <Switch TextureId="10" Comment="求助" IdentificationId="" Name="HelpMe"/>
    <Switch TextureId="23" Comment="瞄准" IdentificationId="" Name="Sniper"/>
    <Switch TextureId="36" Comment="下飞" IdentificationId="" Name="FlyDown"/>
    <Switch TextureId="55" Comment="表情的X" IdentificationId="" Name="BreastPatting"/>
    <Switch TextureId="139" Comment="模拟手（盾牌炮塔）" IdentificationId="" Name="Hand2"/>
    <Switch TextureId="12" Comment="跳伞（单人）" IdentificationId="" Name="Parachute1"/>
    <Switch TextureId="19" Comment="点开快递包" IdentificationId="" Name="ClickPacket"/>
    <Switch TextureId="175" Comment="离开机甲" IdentificationId="" Name="Mecha1"/>
    <Switch TextureId="182" Comment="塔奇克马载具" IdentificationId="" Name="atv1"/>
    <Switch TextureId="176" Comment="取消离开" IdentificationId="" Name="Mecha2"/>
    <Switch TextureId="157" Comment="生化模式解锁鼠标" IdentificationId="" Name="Biochemical2"/>
    <Switch TextureId="136" Comment="坦克夜视1" IdentificationId="" Name="Tank3"/>
    <Switch TextureId="87" Comment="油门" IdentificationId="" Name="Throttle"/>
    <Switch TextureId="53" Comment="白色向左箭头（快递）" IdentificationId="" Name="PacketLeft"/>
    <Switch TextureId="161" Comment="异变围城扳手" IdentificationId="" Name="Spanner"/>
    <Switch TextureId="169" Comment="喷气芯片喷气中" IdentificationId="" Name="Blow1"/>
    <Switch TextureId="167" Comment="特级护甲" IdentificationId="" Name="Tarmor"/>
    <Switch TextureId="29" Comment="换弹药" IdentificationId="" Name="Reload"/>
    <Switch TextureId="50" Comment="选技能的X" IdentificationId="" Name="SkillX"/>
    <Switch TextureId="146" Comment="选择变什么物品（躲猫猫）" IdentificationId="" Name="Transformation"/>
    <Switch TextureId="142" Comment="盾牌炮塔（离开）" IdentificationId="" Name="Turret1"/>
    <Switch TextureId="160" Comment="BR躲猫猫退出" IdentificationId="" Name="Brpeekaboo1"/>
    <Switch TextureId="18" Comment="开眼睛" IdentificationId="" Name="OpenEye"/>
    <Switch TextureId="49" Comment="取消缆绳" IdentificationId="" Name="CancelCable"/>
    <Switch TextureId="9" Comment="无畏战士（团队模式）" IdentificationId="" Name="XS1Goliath"/>
    <Switch TextureId="135" Comment="翻滚（影刃）" IdentificationId="" Name="Roll"/>
    <Switch TextureId="170" Comment="新年手雷" IdentificationId="" Name="Grenadesn"/>
    <Switch TextureId="183" Comment="塔奇克马载具机枪下" IdentificationId="" Name="atv2"/>
    <Switch TextureId="186" Comment="足球" IdentificationId="" Name="football"/>
    <Switch TextureId="40" Comment="取消丢雷" IdentificationId="" Name="CancelFireTheHole"/>
    <Switch TextureId="33" Comment="刹车" IdentificationId="" Name="Brake"/>
    <Switch TextureId="44" Comment="返回游戏" IdentificationId="" Name="ReturnSetUp"/>
    <Switch TextureId="77" Comment="止痛针" IdentificationId="" Name="AnalgesicNeedle"/>
    <Switch TextureId="93" Comment="导弹齐射" IdentificationId="" Name="MissileVolley"/>
    <Switch TextureId="177" Comment="义肢选择" IdentificationId="" Name="choose"/>
    <Switch TextureId="184" Comment="引爆" IdentificationId="" Name="bomb"/>
    <Switch TextureId="2" Comment="上车驾驶" IdentificationId="" Name="GetIntoCar"/>
    <Switch TextureId="178" Comment="义肢使用" IdentificationId="" Name="choose1"/>
    <Switch TextureId="123" Comment="选武器的刀（单挑模式）" IdentificationId="" Name="Knife2"/>
    <Switch TextureId="148" Comment="了断（恶魔岛）" IdentificationId="" Name="Suicide"/>
    <Switch TextureId="158" Comment="生化模式购买机解锁鼠标" IdentificationId="" Name="Biochemical3"/>
    <Switch TextureId="88" Comment="空投" IdentificationId="" Name="Airdrop"/>
    <Switch TextureId="119" Comment="介绍模式的漫画（躲猫猫）" IdentificationId="" Name="Cartoon"/>
    <Switch TextureId="141" Comment="盾牌炮塔（团队模式）" IdentificationId="" Name="Turret"/>
    <Switch TextureId="84" Comment="闪光弹" IdentificationId="" Name="Flash"/>
    <Switch TextureId="179" Comment="小蜜蜂" IdentificationId="" Name="tinybee"/>
    <Switch TextureId="32" Comment="救人" IdentificationId="" Name="Help"/>
    <Switch TextureId="59" Comment="刀（团队模式）" IdentificationId="" Name="Knife"/>
    <Switch TextureId="70" Comment="关上" IdentificationId="" Name="Close"/>
    <Switch TextureId="134" Comment="坦克2" IdentificationId="" Name="Tank2"/>
    <Switch TextureId="74" Comment="手榴弹" IdentificationId="" Name="Grenade"/>
    <Switch TextureId="187" Comment="安装炸弹" IdentificationId="" Name="Bomb1"/>
    <Switch TextureId="76" Comment="止血凝胶" IdentificationId="" Name="HemostaticGel"/>
    <Switch TextureId="89" Comment="小空投" IdentificationId="" Name="Airdrop2"/>
    <Switch TextureId="47" Comment="升级技能" IdentificationId="" Name="SkillUpgrade"/>
    <Switch TextureId="125" Comment="开启功能" IdentificationId="" Name="OpenFunction"/>
    <Switch TextureId="80" Comment="集束炸弹" IdentificationId="" Name="Cluster"/>
    <Switch TextureId="41" Comment="上潜中" IdentificationId="" Name="SwimmingUp"/>
    <Switch TextureId="137" Comment="坦克夜视2" IdentificationId="" Name="Tank4"/>
    <Switch TextureId="35" Comment="上飞" IdentificationId="" Name="FlyUp"/>
    <Switch TextureId="27" Comment="设置的M" IdentificationId="" Name="InSetUp"/>
    <Switch TextureId="46" Comment="选技能的方框" IdentificationId="" Name="SkillCircle"/>
    <Switch TextureId="90" Comment="核弹" IdentificationId="" Name="Missile"/>
    <Switch TextureId="124" Comment="飞机的干扰弹" IdentificationId="" Name="Jamming"/>
    <Switch TextureId="94" Comment="观战队友" IdentificationId="" Name="WatchTeammates"/>
    <Switch TextureId="166" Comment="直升飞机的攻击" IdentificationId="" Name="Helicopter"/>
    <Switch TextureId="126" Comment="黄色三角" IdentificationId="" Name="YellowTriangle"/>
    <Switch TextureId="143" Comment="防弹插板" IdentificationId="" Name="Bulletproof"/>
    <Switch TextureId="3" Comment="下车" IdentificationId="" Name="GetOutCar"/>
    <Switch TextureId="63" Comment="扔回手雷" IdentificationId="" Name="BackGrenade"/>
    <Switch TextureId="173" Comment="防空炮出" IdentificationId="" Name="AAgun2"/>
    <Switch TextureId="118" Comment="雪人手雷" IdentificationId="" Name="Snow"/>
    <Switch TextureId="122" Comment="抬头按住" IdentificationId="" Name="Moto2"/>
    <KeyMapMode ModeID="145" PreviewImage="" Thumbnail="https://static.sj.qq.com/xy/yyb_official_website/oUwQjeas.png" ListImage="" Desciption="" Name="Multi Player" CompatModeID="1">
        <KeyMapSolution SolutionName="MP - 16:9" Version="15634" VersionLog="6ZSu5L2N5L+u5aSN" UpdateTime="1741675121" SilentUpdate="0" SolutionID="145"/>
        <KeyMapSolution SolutionName="MP - 16:10" Version="17179" VersionLog="6ZSu5L2N5pu05paw" UpdateTime="1745995880" SilentUpdate="1" SolutionID="566632"/>
    </KeyMapMode>
    <KeyMapMode ModeID="146" PreviewImage="" Thumbnail="https://static.sj.qq.com/xy/yyb_official_website/oUwQjeas.png" ListImage="" Desciption="" Name="Battle Royale" CompatModeID="2">
        <KeyMapSolution SolutionName="BR - 16:9" Version="12417" VersionLog="6ZSu5L2N5pu05paw" UpdateTime="1735203564" SilentUpdate="0" SolutionID="146"/>
        <KeyMapSolution SolutionName="BR - 16:10" Version="17175" VersionLog="6ZSu5L2N5pu05paw" UpdateTime="1745993949" SilentUpdate="1" SolutionID="566635"/>
    </KeyMapMode>
</Item>
"""

const val OFFICIAL_CONFIG2_VALUE2 = """
<Item ApkName="com.activision.callofduty.shooter">
    <Switch TextureId="86" Comment="弓箭" IdentificationId="" Name="Bow"/>
    <Switch TextureId="149" Comment="夜视仪开" IdentificationId="" Name="Nightvision"/>
    <Switch TextureId="95" Comment="开火模式" IdentificationId="" Name="FireMode2"/>
    <Switch TextureId="130" Comment="购物机向右标志" IdentificationId="" Name="ShoppingMachine"/>
    <Switch TextureId="57" Comment="更换背包" IdentificationId="" Name="SwitchBackpage"/>
    <Switch TextureId="129" Comment="CD的X" IdentificationId="" Name="CDX"/>
    <Switch TextureId="16" Comment="地图打开标志" IdentificationId="" Name="MapOpenFlag"/>
    <Switch TextureId="150" Comment="夜视仪关" IdentificationId="" Name="Nightvision1"/>
    <Switch TextureId="159" Comment="BR躲猫猫摄像头" IdentificationId="" Name="Brpeekaboo"/>
    <Switch TextureId="78" Comment="开局的黄色M" IdentificationId="" Name="YellowM"/>
    <Switch TextureId="171" Comment="战斗机" IdentificationId="" Name="jet"/>
    <Switch TextureId="168" Comment="喷气芯片喷气" IdentificationId="" Name="Blow"/>
    <Switch TextureId="111" Comment="礼物箱" IdentificationId="" Name="Gift"/>
    <Switch TextureId="11" Comment="跳伞（四人）" IdentificationId="" Name="Parachute4"/>
    <Switch TextureId="26" Comment="跳跃" IdentificationId="" Name="Jump"/>
    <Switch TextureId="133" Comment="坦克1" IdentificationId="" Name="Tank1"/>
    <Switch TextureId="68" Comment="弹跳" IdentificationId="" Name="Bounce"/>
    <Switch TextureId="71" Comment="烟雾弹" IdentificationId="" Name="Smoke"/>
    <Switch TextureId="165" Comment="2级背包" IdentificationId="" Name="Backpage2"/>
    <Switch TextureId="38" Comment="下潜" IdentificationId="" Name="SwimDown"/>
    <Switch TextureId="81" Comment="切换手雷" IdentificationId="" Name="SwitchGrenade"/>
    <Switch TextureId="115" Comment="闪光弹（躲猫猫）" IdentificationId="" Name="Flash2"/>
    <Switch TextureId="52" Comment="药物的加号" IdentificationId="" Name="XBtn"/>
    <Switch TextureId="127" Comment="趴下" IdentificationId="" Name="Fall"/>
    <Switch TextureId="151" Comment="暴风雨（团队模式）" IdentificationId="" Name="Rainstorm"/>
    <Switch TextureId="172" Comment="防空炮进" IdentificationId="" Name="AAgun"/>
    <Switch TextureId="58" Comment="方向轮盘" IdentificationId="" Name="SteeringWheel"/>
    <Switch TextureId="163" Comment="普通护甲" IdentificationId="" Name="Carmor"/>
    <Switch TextureId="189" Comment="新地图解锁2" IdentificationId="" Name="newmap2"/>
    <Switch TextureId="140" Comment="爬楼梯（团队模式）" IdentificationId="" Name="Stair"/>
    <Switch TextureId="13" Comment="开伞" IdentificationId="" Name="Parachute2"/>
    <Switch TextureId="51" Comment="白色向下箭头" IdentificationId="" Name="PickupDown"/>
    <Switch TextureId="61" Comment="选择开火模式的左边框" IdentificationId="" Name="SelectFireMode"/>
    <Switch TextureId="72" Comment="震爆弹" IdentificationId="" Name="Detonation"/>
    <Switch TextureId="54" Comment="取消趴下" IdentificationId="" Name="CancelFall"/>
    <Switch TextureId="24" Comment="蹲下" IdentificationId="" Name="Squat"/>
    <Switch TextureId="154" Comment="滑雪板跳" IdentificationId="" Name="Skijump"/>
    <Switch TextureId="6" Comment="乘车" IdentificationId="" Name="ByCar"/>
    <Switch TextureId="82" Comment="拾取防爆装置" IdentificationId="" Name="TrophySystem"/>
    <Switch TextureId="14" Comment="疾跑" IdentificationId="" Name="Run"/>
    <Switch TextureId="91" Comment="感应弹" IdentificationId="" Name="Induction"/>
    <Switch TextureId="155" Comment="防弹衣" IdentificationId="" Name="Armor"/>
    <Switch TextureId="1" Comment="开关门" IdentificationId="" Name="DoorOpen"/>
    <Switch TextureId="17" Comment="眼睛" IdentificationId="" Name="Eye"/>
    <Switch TextureId="144" Comment="选择手雷解锁鼠标（爆破模式）" IdentificationId="" Name="Boomf"/>
    <Switch TextureId="147" Comment="缆车（恶魔岛）" IdentificationId="" Name="Telpher"/>
    <Switch TextureId="62" Comment="拆弹）" IdentificationId="" Name="BombDisposal"/>
    <Switch TextureId="174" Comment="进入机甲" IdentificationId="" Name="Mecha"/>
    <Switch TextureId="34" Comment="刹车,按着" IdentificationId="" Name="Brake2"/>
    <Switch TextureId="60" Comment="更换武器）" IdentificationId="" Name="SwitchWeapon"/>
    <Switch TextureId="37" Comment="上潜" IdentificationId="" Name="SwimUp"/>
    <Switch TextureId="92" Comment="切换位置" IdentificationId="" Name="SwitchingPosition"/>
    <Switch TextureId="145" Comment="盾牌（团队模式）" IdentificationId="" Name="Shield1"/>
    <Switch TextureId="7" Comment="鸣笛" IdentificationId="" Name="Whistle"/>
    <Switch TextureId="42" Comment="下潜中" IdentificationId="" Name="SwimmingDown"/>
    <Switch TextureId="132" Comment="影刃（团队模式）" IdentificationId="" Name="ShadowBlade"/>
    <Switch TextureId="8" Comment="点开捡物" IdentificationId="" Name="ClickPickupDown"/>
    <Switch TextureId="180" Comment="拳套" IdentificationId="" Name="box"/>
    <Switch TextureId="185" Comment="直升机炮手" IdentificationId="" Name="gunner"/>
    <Switch TextureId="190" Comment="新地图解锁3" IdentificationId="" Name="newmap3"/>
    <Switch TextureId="181" Comment="塔奇克马载具机枪" IdentificationId="" Name="atv"/>
    <Switch TextureId="73" Comment="毒气弹" IdentificationId="" Name="Gas"/>
    <Switch TextureId="64" Comment="挂机后的边框" IdentificationId="" Name="HangUp"/>
    <Switch TextureId="98" Comment="语音按住" IdentificationId="" Name="Voice"/>
    <Switch TextureId="21" Comment="开火模式（左）" IdentificationId="" Name="FireMode1"/>
    <Switch TextureId="30" Comment="设置" IdentificationId="" Name="SetUp"/>
    <Switch TextureId="188" Comment="新地图解锁1" IdentificationId="" Name="newmap1"/>
    <Switch TextureId="69" Comment="展开" IdentificationId="" Name="Open"/>
    <Switch TextureId="83" Comment="连环闪光弹" IdentificationId="" Name="SerialFlash"/>
    <Switch TextureId="75" Comment="急救包" IdentificationId="" Name="FirstAidKit"/>
    <Switch TextureId="153" Comment="滑雪板" IdentificationId="" Name="Ski"/>
    <Switch TextureId="116" Comment="空投（一击必杀）" IdentificationId="" Name="Airdrop3"/>
    <Switch TextureId="162" Comment="异变围城购买解锁" IdentificationId="" Name="Change"/>
    <Switch TextureId="174" Comment="油门2" IdentificationId="" Name="Throttle2"/>
    <Switch TextureId="31" Comment="表情" IdentificationId="" Name="Emoji"/>
    <Switch TextureId="25" Comment="取消蹲下" IdentificationId="" Name="CancelSquat"/>
    <Switch TextureId="138" Comment="新空投" IdentificationId="" Name="Airdrop4"/>
    <Switch TextureId="43" Comment="鸣笛中" IdentificationId="" Name="Whistling"/>
    <Switch TextureId="121" Comment="抬头" IdentificationId="" Name="Moto1"/>
    <Switch TextureId="128" Comment="CD" IdentificationId="" Name="CD"/>
    <Switch TextureId="48" Comment="缆绳" IdentificationId="" Name="Cable"/>
    <Switch TextureId="152" Comment="歼灭者（团队模式）" IdentificationId="" Name="Annihilator"/>
    <Switch TextureId="164" Comment="高级护甲" IdentificationId="" Name="Aarmor"/>
    <Switch TextureId="28" Comment="取消瞄准" IdentificationId="" Name="Sniper2"/>
    <Switch TextureId="10" Comment="求助" IdentificationId="" Name="HelpMe"/>
    <Switch TextureId="23" Comment="瞄准" IdentificationId="" Name="Sniper"/>
    <Switch TextureId="36" Comment="下飞" IdentificationId="" Name="FlyDown"/>
    <Switch TextureId="55" Comment="表情的X" IdentificationId="" Name="BreastPatting"/>
    <Switch TextureId="139" Comment="模拟手（盾牌炮塔）" IdentificationId="" Name="Hand2"/>
    <Switch TextureId="12" Comment="跳伞（单人）" IdentificationId="" Name="Parachute1"/>
    <Switch TextureId="19" Comment="点开快递包" IdentificationId="" Name="ClickPacket"/>
    <Switch TextureId="175" Comment="离开机甲" IdentificationId="" Name="Mecha1"/>
    <Switch TextureId="182" Comment="塔奇克马载具" IdentificationId="" Name="atv1"/>
    <Switch TextureId="176" Comment="取消离开" IdentificationId="" Name="Mecha2"/>
    <Switch TextureId="157" Comment="生化模式解锁鼠标" IdentificationId="" Name="Biochemical2"/>
    <Switch TextureId="136" Comment="坦克夜视1" IdentificationId="" Name="Tank3"/>
    <Switch TextureId="87" Comment="油门" IdentificationId="" Name="Throttle"/>
    <Switch TextureId="53" Comment="白色向左箭头（快递）" IdentificationId="" Name="PacketLeft"/>
    <Switch TextureId="161" Comment="异变围城扳手" IdentificationId="" Name="Spanner"/>
    <Switch TextureId="169" Comment="喷气芯片喷气中" IdentificationId="" Name="Blow1"/>
    <Switch TextureId="167" Comment="特级护甲" IdentificationId="" Name="Tarmor"/>
    <Switch TextureId="29" Comment="换弹药" IdentificationId="" Name="Reload"/>
    <Switch TextureId="50" Comment="选技能的X" IdentificationId="" Name="SkillX"/>
    <Switch TextureId="146" Comment="选择变什么物品（躲猫猫）" IdentificationId="" Name="Transformation"/>
    <Switch TextureId="142" Comment="盾牌炮塔（离开）" IdentificationId="" Name="Turret1"/>
    <Switch TextureId="160" Comment="BR躲猫猫退出" IdentificationId="" Name="Brpeekaboo1"/>
    <Switch TextureId="18" Comment="开眼睛" IdentificationId="" Name="OpenEye"/>
    <Switch TextureId="49" Comment="取消缆绳" IdentificationId="" Name="CancelCable"/>
    <Switch TextureId="9" Comment="无畏战士（团队模式）" IdentificationId="" Name="XS1Goliath"/>
    <Switch TextureId="135" Comment="翻滚（影刃）" IdentificationId="" Name="Roll"/>
    <Switch TextureId="170" Comment="新年手雷" IdentificationId="" Name="Grenadesn"/>
    <Switch TextureId="183" Comment="塔奇克马载具机枪下" IdentificationId="" Name="atv2"/>
    <Switch TextureId="186" Comment="足球" IdentificationId="" Name="football"/>
    <Switch TextureId="40" Comment="取消丢雷" IdentificationId="" Name="CancelFireTheHole"/>
    <Switch TextureId="33" Comment="刹车" IdentificationId="" Name="Brake"/>
    <Switch TextureId="44" Comment="返回游戏" IdentificationId="" Name="ReturnSetUp"/>
    <Switch TextureId="77" Comment="止痛针" IdentificationId="" Name="AnalgesicNeedle"/>
    <Switch TextureId="93" Comment="导弹齐射" IdentificationId="" Name="MissileVolley"/>
    <Switch TextureId="177" Comment="义肢选择" IdentificationId="" Name="choose"/>
    <Switch TextureId="184" Comment="引爆" IdentificationId="" Name="bomb"/>
    <Switch TextureId="2" Comment="上车驾驶" IdentificationId="" Name="GetIntoCar"/>
    <Switch TextureId="178" Comment="义肢使用" IdentificationId="" Name="choose1"/>
    <Switch TextureId="123" Comment="选武器的刀（单挑模式）" IdentificationId="" Name="Knife2"/>
    <Switch TextureId="148" Comment="了断（恶魔岛）" IdentificationId="" Name="Suicide"/>
    <Switch TextureId="158" Comment="生化模式购买机解锁鼠标" IdentificationId="" Name="Biochemical3"/>
    <Switch TextureId="88" Comment="空投" IdentificationId="" Name="Airdrop"/>
    <Switch TextureId="119" Comment="介绍模式的漫画（躲猫猫）" IdentificationId="" Name="Cartoon"/>
    <Switch TextureId="141" Comment="盾牌炮塔（团队模式）" IdentificationId="" Name="Turret"/>
    <Switch TextureId="84" Comment="闪光弹" IdentificationId="" Name="Flash"/>
    <Switch TextureId="179" Comment="小蜜蜂" IdentificationId="" Name="tinybee"/>
    <Switch TextureId="32" Comment="救人" IdentificationId="" Name="Help"/>
    <Switch TextureId="59" Comment="刀（团队模式）" IdentificationId="" Name="Knife"/>
    <Switch TextureId="70" Comment="关上" IdentificationId="" Name="Close"/>
    <Switch TextureId="134" Comment="坦克2" IdentificationId="" Name="Tank2"/>
    <Switch TextureId="74" Comment="手榴弹" IdentificationId="" Name="Grenade"/>
    <Switch TextureId="187" Comment="安装炸弹" IdentificationId="" Name="Bomb1"/>
    <Switch TextureId="76" Comment="止血凝胶" IdentificationId="" Name="HemostaticGel"/>
    <Switch TextureId="89" Comment="小空投" IdentificationId="" Name="Airdrop2"/>
    <Switch TextureId="47" Comment="升级技能" IdentificationId="" Name="SkillUpgrade"/>
    <Switch TextureId="125" Comment="开启功能" IdentificationId="" Name="OpenFunction"/>
    <Switch TextureId="80" Comment="集束炸弹" IdentificationId="" Name="Cluster"/>
    <Switch TextureId="41" Comment="上潜中" IdentificationId="" Name="SwimmingUp"/>
    <Switch TextureId="137" Comment="坦克夜视2" IdentificationId="" Name="Tank4"/>
    <Switch TextureId="35" Comment="上飞" IdentificationId="" Name="FlyUp"/>
    <Switch TextureId="27" Comment="设置的M" IdentificationId="" Name="InSetUp"/>
    <Switch TextureId="46" Comment="选技能的方框" IdentificationId="" Name="SkillCircle"/>
    <Switch TextureId="90" Comment="核弹" IdentificationId="" Name="Missile"/>
    <Switch TextureId="124" Comment="飞机的干扰弹" IdentificationId="" Name="Jamming"/>
    <Switch TextureId="94" Comment="观战队友" IdentificationId="" Name="WatchTeammates"/>
    <Switch TextureId="166" Comment="直升飞机的攻击" IdentificationId="" Name="Helicopter"/>
    <Switch TextureId="126" Comment="黄色三角" IdentificationId="" Name="YellowTriangle"/>
    <Switch TextureId="143" Comment="防弹插板" IdentificationId="" Name="Bulletproof"/>
    <Switch TextureId="3" Comment="下车" IdentificationId="" Name="GetOutCar"/>
    <Switch TextureId="63" Comment="扔回手雷" IdentificationId="" Name="BackGrenade"/>
    <Switch TextureId="173" Comment="防空炮出" IdentificationId="" Name="AAgun2"/>
    <Switch TextureId="118" Comment="雪人手雷" IdentificationId="" Name="Snow"/>
    <Switch TextureId="122" Comment="抬头按住" IdentificationId="" Name="Moto2"/>
    <KeyMapMode ModeID="145" PreviewImage="" Thumbnail="https://static.sj.qq.com/xy/yyb_official_website/oUwQjeas.png" ListImage="" Desciption="" Name="团队竞技模式" CompatModeID="1">
        <KeyMapSolution SolutionName="官方默认方案" Version="0" VersionLog="" UpdateTime="1752061397" SilentUpdate="0" SolutionID="21274"/>
    </KeyMapMode>
</Item>
"""